name: ip_geolocation_api
description: A dart package to flutter or dart projects to get your geolocation data from your IP
version: 0.0.1
author: Darwin Morocho
homepage: https://github.com/darwin-morocho/dart-ip-geolocation-api


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+3
  meta: ^1.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter
