name: ip_geolocation_api
description: A new Flutter package project.
version: 0.0.1
author: Darwin Morocho
homepage: https://dina.ec

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+3
  meta: ^1.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter
